<?php

namespace Decoyeso\EstadisticaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GraficoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraficoRepository extends EntityRepository
{
}