<?php

namespace Decoyeso\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudMovimientoRepository extends EntityRepository
{
}