<?php

namespace Decoyeso\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StockProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockProductoRepository extends EntityRepository
{
}