ProductoBundle:
    resource: "@ProductoBundle/Resources/config/routing/producto.yml"
    prefix: /producto

ServicioBundle:
    resource: "@ProductoBundle/Resources/config/routing/servicio.yml"
    prefix: /servicio

InsumoBundle:
    resource: "@ProductoBundle/Resources/config/routing/insumo.yml"
    prefix: /insumo