obra:
    pattern:  /
    defaults: { _controller: "DecoyesoObraBundle:Obra:index" }

obra_show:
    pattern:  /{id}/show
    defaults: { _controller: "DecoyesoObraBundle:Obra:show" }

obra_new:
    pattern:  /new
    defaults: { _controller: "DecoyesoObraBundle:Obra:new" }

obra_create:
    pattern:  /create
    defaults: { _controller: "DecoyesoObraBundle:Obra:create" }
    requirements: { _method: post }

obra_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DecoyesoObraBundle:Obra:edit" }

obra_update:
    pattern:  /{id}/update
    defaults: { _controller: "DecoyesoObraBundle:Obra:update" }
    requirements: { _method: post }

obra_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DecoyesoObraBundle:Obra:delete" }
    requirements: { _method: post }
