obra:
    pattern:  /{pararouting}
    defaults: { _controller: "ObraBundle:Obra:index", pararouting:index }
    requirements:
        pararouting: buscar

obra_show:
    pattern:  /{id}/show
    defaults: { _controller: "ObraBundle:Obra:show" }

obra_edit_from_pedido:
    pattern:  /{paramPedido}/editfrompedido
    defaults: { _controller: "ObraBundle:Obra:editFromPedido" }

obra_new:
    pattern:  /new
    defaults: { _controller: "ObraBundle:Obra:new" }
    
obra_new_from_pedido:
    pattern:  /{pedido}/newfrompedido
    defaults: { _controller: "ObraBundle:Obra:newFromPedido" }

obra_create:
    pattern:  /create
    defaults: { _controller: "ObraBundle:Obra:create" }
    requirements: { _method: post }

obra_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ObraBundle:Obra:edit" }

obra_update:
    pattern:  /{id}/update
    defaults: { _controller: "ObraBundle:Obra:update" }
    requirements: { _method: post }

obra_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ObraBundle:Obra:delete" }
    requirements: { _method: post }
