grafico:
    pattern:  /
    defaults: { _controller: "DecoyesoEstadisticaBundle:Grafico:index" }

grafico_modulo:
    pattern:  /graficos/{modulo}
    defaults: { _controller: "DecoyesoEstadisticaBundle:Grafico:mostrarGraficosModulo" }
    
grafico_show:
    pattern:  /graficos/show/{grafico}
    defaults: { _controller: "DecoyesoEstadisticaBundle:Grafico:mostrarGraficoIndividual" }
    

    


    

