MovimientoStockBundle:
    resource: "@StockBundle/Resources/config/routing/movimientostock.yml"
    prefix: /movimientostock

SolicitudMovimientoBundle:
    resource: "@StockBundle/Resources/config/routing/solicitudmovimiento.yml"
    prefix: /solicitudmovimiento