parameters:
#    decoyeso_obra.example.class: Decoyeso\ObraBundle\Example

services:
#    decoyeso_obra.example:
#        class: %decoyeso_obra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
