<?php

namespace Decoyeso\ProduccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LugarSecadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarSecadorRepository extends EntityRepository
{
}