<?php

namespace Decoyeso\ProduccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoldeRepository extends EntityRepository
{
}