proceso:
    pattern:  /
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:index" }

proceso_show:
    pattern:  /{id}/show
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:show" }

proceso_new:
    pattern:  /new
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:new" }

proceso_create:
    pattern:  /create
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:create" }
    requirements: { _method: post }

proceso_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:edit" }

proceso_update:
    pattern:  /{id}/update
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:update" }
    requirements: { _method: post }

proceso_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:delete" }
    requirements: { _method: post }
    
proceso_items:
    pattern:  /items
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:getItems" }

proceso_iniciar:
    pattern:  /{id}/iniciar
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:iniciar" }

proceso_finalizar:
    pattern:  /{id}/finalizar
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:finalizar" }

proceso_finalizar_update:
    pattern:  /{id}/finalizar_update
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:finalizarUpdate" }

proceso_asignar:
    pattern:  /{id}/asignar
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:asignarProductosAlStock" }
    
proceso_asignar_update:
    pattern:  /{id}/asignar_update
    defaults: { _controller: "DecoyesoProduccionBundle:Proceso:asignarProductosAlStockUpdate" }




